[versions]
androidx-room = "2.8.4"
kotlin = "2.3.10"
metro = "0.10.4"

[plugins]
android-application = { id = "com.android.application", version = "9.0.1" }
android-library = { id = "com.android.library", version = "9.0.1" }
convention-android-application = { id = "convention-android-application" }
convention-android-library = { id = "convention-android-library" }
convention-jvm-library = { id = "convention-jvm-library" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.5" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

[libraries]
android-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
androidx-activity-compose = "androidx.activity:activity-compose:1.12.4"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.11.0-alpha05"
androidx-compose-material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.8"
androidx-compose-material3 = "androidx.compose.material3:material3:1.5.0-alpha14"
androidx-compose-runtime = "androidx.compose.runtime:runtime:1.11.0-alpha05"
androidx-compose-ui = "androidx.compose.ui:ui:1.11.0-alpha05"
androidx-core = "androidx.core:core:1.17.0"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0"
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
google-material = "com.google.android.material:material:1.13.0"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
metrox-android = { module = "dev.zacsweers.metro:metrox-android", version.ref = "metro" }
metrox-viewmodel-compose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }
